import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import Box from "../components/Box";
import styles from "../styles/Home.module.css";
import Head from "next/head";
export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Inmart Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ position: "absolute" }}>
          <h1 className={styles.title}>Inmart Tech</h1>

          <p className={styles.description}>
            We build awesome Web & Mobile Apps
          </p>
        </div>
        <div className={styles.threejs}>
          <Canvas camera={{ position: [-5, 0, 45] }}>
            <ambientLight intensity={1} />
            <pointLight position={[-65, 5, 55]} intensity={2} />
            <Box logo="react.png" position={[85, 0, 50]} endPos={[10, 0, 9]} />
            <Box
              logo="next.png"
              position={[-74, 0, 40]}
              endPos={[-10, 0, 13]}
            />
            <Box logo="js.png" position={[60, 10, 35]} endPos={[0, 10, 11]} />
            <Box
              logo="aws.png"
              position={[-95, -10, 25]}
              endPos={[0, -10, 10]}
            ></Box>
            <OrbitControls
              minAzimuthAngle={-0.6}
              maxAzimuthAngle={0.6}
              minPolarAngle={1.25}
              maxPolarAngle={1.8}
              enableZoom={false}
            />
          </Canvas>
        </div>
      </main>
    </>
  );
}
