import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import Box from "../components/Box";
import styles from "../styles/Home.module.css";
import Head from "next/head";
export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Inmart Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ position: "absolute"}}>
        <h1 className={styles.title}>Inmart Tech</h1>

        <p className={styles.description}>We build awesome Web & Mobile Apps</p>
        </div>
        <div className={styles.threejs}>
          <Canvas camera={{ position: [-5, 0, 45] }}>
            <ambientLight intensity={1} />
            <pointLight position={[-10, 5, 55]} intensity={2} />
            <Box logo="react.png" position={[10, 0, 50]} endPos={9} />
            <Box logo="next.png" position={[-10, 0, 40]} endPos={13} />
            <Box logo="js.png" position={[0, 10, 35]} endPos={11} />
            <Box logo="aws.png" position={[0, -10, 25]} endPos={10}></Box>
            <OrbitControls
              minAzimuthAngle={-0.8}
              maxAzimuthAngle={0.8}
              minPolarAngle={1}
              maxPolarAngle={2}
              enableZoom={false}
            />
          </Canvas>
        </div>
      </main>
      
    </>
  );
}
